sudo: required

services:
  - docker

language: c

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

script:
  # Install required ansible roles
  - docker build -t suizman/dmux:latest .

after_success:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" -e "$DOCKER_EMAIL"
  - docker push suizman/dmux:latest
  - rm /home/travis/.docker/config.json

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1714c7510a07d4a44c2d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
